### ISSUE TITLE
Update localizations for incoming update

### ISSUE THREAD

**Issue by copygirl** [copygirl/WearableBackpacks#57]
- [x] `de_DE` - @Vexatos (#58)
- [x] `zh_CN` - @3TUSK, @TartaricAcid (#56, #59)
- [x] `nl_NL` - @TDarkShadow (#60)
- [x] **NEW!** `da_DK` - @Zerotiger (#55)
- [x] **NEW!** `it_IT` - @Insane-96 (#51)
- [x] `ru_RU` - @kirill3345, @dangranos, @raspopov (#61)
- [x] `pt_BR` - @wenlfs, @eduardogomesv (#62)
- [ ] `es_MX` - @Dorzar
- [ ] `ko_KR` - @tinywolf3

There should not be any further localization changes.

**Comment by TDarkShadow** [comment]
I've done my part 💪

**Comment by Zerotiger** [comment]
That should be it for me as well (#55)

**Comment by Insane-96** [comment]
Same. #51

**Comment by raspopov** [comment]
Russian here: https://github.com/copygirl/WearableBackpacks/pull/61

**Comment by eduardogomesv** [comment]
Done! I guess.
